from toyRF import EasyEnv

env = EasyEnv()
print("Initial Test")
print("Reset: {}".format(env.reset()))
print("Dimension: {}".format(env.obs_dim()))


print("Reset: {}".format(env.reset()))
new_obs, stopSignal, reward = env.step(1)
print("1. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))
new_obs, stopSignal, reward = env.step(1)
print("2. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))
new_obs, stopSignal, reward = env.step(1)
print("3. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))
new_obs, stopSignal, reward = env.step(1)
print("4. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))
new_obs, stopSignal, reward = env.step(1)
print("5. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))
new_obs, stopSignal, reward = env.step(1)
print("6. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))
new_obs, stopSignal, reward = env.step(1)
print("7. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))
new_obs, stopSignal, reward = env.step(1)
print("8. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))
new_obs, stopSignal, reward = env.step(1)
print("9. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))
new_obs, stopSignal, reward = env.step(1)
print("10. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))
new_obs, stopSignal, reward = env.step(1)
print("11. Step after Reset\nnew_obs: {},stopSignal: {},Reward: {}".format(new_obs, stopSignal, reward))